import {StyleSheet} from 'react-native';
export default styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    video: {
      position: 'absolute',
      top: 0,
      left: 0,
      bottom: 0,
      right: 0,
    },
    content: {
      flex: 1,
      flexDirection: 'column',
      justifyContent: 'space-evenly',
      alignItems: 'center',
      margin: 30,
    },
    text: {
      fontFamily: 'WorkSans-Regular',
      fontStyle: 'normal',
      fontSize: 25,
      lineHeight: 35,
      letterSpacing: 0.5,
      color: '#ffffff',
    },
    textInput: {
      width: 325,
      height: 51,
      backgroundColor: '#4aade9',
      opacity: 0.7,
      color: '#FFFFFF',
      fontFamily: 'WorkSans-Regular',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: 20,
      lineHeight: 23,
      letterSpacing: 1,
      borderWidth: 2,
      borderStyle: 'solid',
      borderColor: '#FFFAFA',
      borderRadius: 10,
      paddingLeft: 30,
    },
    placeholder: {
      paddingLeft: 30,
      borderColor: '#FFFFFF',
      fontFamily: 'WorkSans-Regular',
      fontStyle: 'normal',
      fontWeight: 'normal',
      fontSize: 20,
      lineHeight: 23,
      letterSpacing: 1,
    },
    header: {
      marginTop: 10,
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    nextButton: {
      alignSelf: 'flex-end',
    },
});
  